language: node_js
node_js:
- stable
notifications:
  slack:
    secure: pv1Pqi3Ma+AAdy+Ho9wZ/lBAgzGjGDdMfggHZCPzq+efxyFlAG3QECcqMiSZVeTt6W0XlpF08/aBTm5dV2IktwReOBSBg0z2D9Q/gVi1Ce3I4HBrGbR0ujNXu4/7DEWniCvecuJYTJWqN0EV/25X89qbxyJtK2TV2tg16nD3NElH1V/0wpMUu8hXfXWbDSmsilAMsBOPPceoHad3mpmZjfeWrUA6Ksb34bCQvShVi5R5yAPLO/MLqvT44LIzW772jNC091FGFzJsmAcQkpZbAkLbZj+QX5ALnkzVhkqpyGlQwyRrqSfXhYLoH/YRSGpW8FDrJdSADYsqv4a5liZhxjY+YUnErvPhbpQWjNBpt1+0IRdESexK2EC1gOMhLt7qeESuaSXER5HQrr3nxTMb6cuCLwdKGTdzmv+C+WMNPaJ6CmRcSdZryK3PQyLxRF4Q0khVKBUdVuGwb4Rj8X5ge99bCrhZgYQ27d4wIqpb6YlZAaM5b+JO8CANRV1W8Czen+iIvpLwi/r6DlYYbeQhF/axRfx5zff6LiwXQFThbhkVtTy4UeAPe1cyczPFIDY9Z4coTdB0Mh40nMpwQ1zTg961jGdUTT78Ksm1LGU2pNN7JeUsAyKvoxpjsVam09Llg1KSwRbdYdB8Z5UQJCjMjUrJq3OFPFf3N+KucJO7DVc=
